### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by santiagoaguiar** [elliotf/chai-fuzzy#10]
`underscore` is not listed on the `dependencies` of chai-fuzzy, only on `devDependencies`, so it fails unless underscore is added as a dependency of the parent project.

**Comment by AriaMinaei** [comment]
+1

**Comment by elliotf** [comment]
@santiagoaguiar you should have received a warning that underscore is a required peer dependency.  Did you not get that warning?

**Comment by santiagoaguiar** [comment]
I might have ;) I'll admit I hit the issue while removing the underscore dep since I didn't needed it any longer. 

I'm not sure why `chai-fuzzy` requires me to have `underscore` installed anyway, aren't the asserts provided by `chai-fuzzy` useful even if you aren't using `underscore`?

**Comment by elliotf** [comment]
The assertions are still useful, I suppose, but I chose to have it as a
peer dependency because it's used so often, and rather than installing one
more (potentially different) version of underscore, why not just let the
caller specify the version?

To be honest, I don't use this library any more; I just use vanilla chai.

**Comment by santiagoaguiar** [comment]
OK, to be honest, I added it as a dev-dep for some tests but not using the assertions currently :), but they do seem useful for other people on the team that write tests so I left them there. 

I use `lodash` instead of underscore, so that's why I dont need to add the underscore dep. 

OTOH, it shouldn't break anything to change `underscore` to be a dep of `chai-fuzzy`, and I can't see why it would be a problem (and you could argue that for the functionality of underscore that you use, it might be safer to stick to a given version).

**Comment by elliotf** [comment]
Very fair arguments.  I might also update the documentation to provide vanilla chai equivalents to the assertions in this library.

My memory is fuzzy from three years ago, but I think that I created this library because chai's non-strict assertion didn't work.  Or I didn't know what I was doing.

**Comment by elliotf** [comment]
underscore is now a direct dependency of chai-fuzzy, since #12 and v1.6.0
