### ISSUE TITLE
how is this different from deep.equal ?

### ISSUE THREAD

**Issue by stevenvachon** [elliotf/chai-fuzzy#14]
I had thought that this would be possible:
```js
expect({ key1:0, key2:1 }).to.be.like({ key1:0 });
```

but it just seems to perform like `deep.equal()`, which is already provided by Mocha. I'm confused.

---

**Edit**: the functionality that I'd expected above in my code sample is made possible with [chai-like](https://npmjs.com/chai-like).

**Comment by elliotf** [comment]
:+1: to chai-like!

This module is probably pretty useless.  `deep.equal()` either didn't exist or I didn't know about it.

Suggestions welcome for how to deal with the less-than-useful nature of this module.  :)

**Comment by elliotf** [comment]
For future readers, `.like` appears to be a reinvention of `.deep.equal` and is probably not what you want.

It looks like deep.equal is circa May 2012, so my past self from Oct 2012 was probably just not aware of it.
